name: Gerar APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar projeto
        uses: actions/checkout@v4

      - name: Instalar Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: false

      - name: Preparar Android
        run: bash scripts/prepare_android.sh

      - name: Limpar dependências antigas
        run: |
          flutter clean
          rm -rf .dart_tool
          rm -rf build
          flutter pub get

      - name: Gerar APK release
        run: flutter build apk --release

      - name: Disponibilizar APK
        uses: actions/upload-artifact@v4
        with:
          name: ConsultaNF-MR-APK
          path: build/app/outputs/flutter-apk/app-release.apk
